class Region {
  String? iso;
  String? englishName;
  String? foreignName;

  Region({this.iso, this.englishName, this.foreignName});

  factory Region.fromJson(Map<String, dynamic> json) {
    return Region(
      iso: json['iso'],
      englishName: json['englishName'],
      foreignName: json['nativeName'],
    );
  }
}

final List<Region> availableRegions = [
  Region(iso: "AD", englishName: "Andorra", foreignName: "Andorra"),
  Region(iso: "AE", englishName: "United Arab Emirates", foreignName: "United Arab Emirates"),
  Region(iso: "AG", englishName: "Antigua and Barbuda", foreignName: "Antigua & Barbuda"),
  Region(iso: "AL", englishName: "Albania", foreignName: "Albania"),
  Region(iso: "AO", englishName: "Angola", foreignName: "Angola"),
  Region(iso: "AR", englishName: "Argentina", foreignName: "Argentina"),
  Region(iso: "AT", englishName: "Austria", foreignName: "Austria"),
  Region(iso: "AU", englishName: "Australia", foreignName: "Australia"),
  Region(iso: "AZ", englishName: "Azerbaijan", foreignName: "Azerbaijan"),
  Region(iso: "BA", englishName: "Bosnia and Herzegovina", foreignName: "Bosnia & Herzegovina"),
  Region(iso: "BB", englishName: "Barbados", foreignName: "Barbados"),
  Region(iso: "BE", englishName: "Belgium", foreignName: "Belgium"),
  Region(iso: "BF", englishName: "Burkina Faso", foreignName: "Burkina Faso"),
  Region(iso: "BG", englishName: "Bulgaria", foreignName: "Bulgaria"),
  Region(iso: "BH", englishName: "Bahrain", foreignName: "Bahrain"),
  Region(iso: "BM", englishName: "Bermuda", foreignName: "Bermuda"),
  Region(iso: "BO", englishName: "Bolivia", foreignName: "Bolivia"),
  Region(iso: "BR", englishName: "Brazil", foreignName: "Brazil"),
  Region(iso: "BS", englishName: "Bahamas", foreignName: "Bahamas"),
  Region(iso: "BY", englishName: "Belarus", foreignName: "Belarus"),
  Region(iso: "BZ", englishName: "Belize", foreignName: "Belize"),
  Region(iso: "CA", englishName: "Canada", foreignName: "Canada"),
  Region(iso: "CD", englishName: "Congo", foreignName: "Democratic Republic of the Congo (Kinshasa)"),
  Region(iso: "CH", englishName: "Switzerland", foreignName: "Switzerland"),
  Region(iso: "CI", englishName: "Cote D'Ivoire", foreignName: "Côte d’Ivoire"),
  Region(iso: "CL", englishName: "Chile", foreignName: "Chile"),
  Region(iso: "CM", englishName: "Cameroon", foreignName: "Cameroon"),
  Region(iso: "CO", englishName: "Colombia", foreignName: "Colombia"),
  Region(iso: "CR", englishName: "Costa Rica", foreignName: "Costa Rica"),
  Region(iso: "CU", englishName: "Cuba", foreignName: "Cuba"),
  Region(iso: "CV", englishName: "Cape Verde", foreignName: "Cape Verde"),
  Region(iso: "CY", englishName: "Cyprus", foreignName: "Cyprus"),
  Region(iso: "CZ", englishName: "Czech Republic", foreignName: "Czech Republic"),
  Region(iso: "DE", englishName: "Germany", foreignName: "Germany"),
  Region(iso: "DK", englishName: "Denmark", foreignName: "Denmark"),
  Region(iso: "DO", englishName: "Dominican Republic", foreignName: "Dominican Republic"),
  Region(iso: "DZ", englishName: "Algeria", foreignName: "Algeria"),
  Region(iso: "EC", englishName: "Ecuador", foreignName: "Ecuador"),
  Region(iso: "EE", englishName: "Estonia", foreignName: "Estonia"),
  Region(iso: "EG", englishName: "Egypt", foreignName: "Egypt"),
  Region(iso: "ES", englishName: "Spain", foreignName: "Spain"),
  Region(iso: "FI", englishName: "Finland", foreignName: "Finland"),
  Region(iso: "FJ", englishName: "Fiji", foreignName: "Fiji"),
  Region(iso: "FR", englishName: "France", foreignName: "France"),
  Region(iso: "GB", englishName: "United Kingdom", foreignName: "United Kingdom"),
  Region(iso: "GF", englishName: "French Guiana", foreignName: "French Guiana"),
  Region(iso: "GH", englishName: "Ghana", foreignName: "Ghana"),
  Region(iso: "GI", englishName: "Gibraltar", foreignName: "Gibraltar"),
  Region(iso: "GP", englishName: "Guadeloupe", foreignName: "Guadeloupe"),
  Region(iso: "GQ", englishName: "Equatorial Guinea", foreignName: "Equatorial Guinea"),
  Region(iso: "GR", englishName: "Greece", foreignName: "Greece"),
  Region(iso: "GT", englishName: "Guatemala", foreignName: "Guatemala"),
  Region(iso: "GY", englishName: "Guyana", foreignName: "Guyana"),
  Region(iso: "HK", englishName: "Hong Kong", foreignName: "Hong Kong"),
  Region(iso: "HN", englishName: "Honduras", foreignName: "Honduras"),
  Region(iso: "HR", englishName: "Croatia", foreignName: "Croatia"),
  Region(iso: "HU", englishName: "Hungary", foreignName: "Hungary"),
  Region(iso: "ID", englishName: "Indonesia", foreignName: "Indonesia"),
  Region(iso: "IE", englishName: "Ireland", foreignName: "Ireland"),
  Region(iso: "IL", englishName: "Israel", foreignName: "Israel"),
  Region(iso: "IN", englishName: "India", foreignName: "India"),
  Region(iso: "IQ", englishName: "Iraq", foreignName: "Iraq"),
  Region(iso: "IS", englishName: "Iceland", foreignName: "Iceland"),
  Region(iso: "IT", englishName: "Italy", foreignName: "Italy"),
  Region(iso: "JM", englishName: "Jamaica", foreignName: "Jamaica"),
  Region(iso: "JO", englishName: "Jordan", foreignName: "Jordan"),
  Region(iso: "JP", englishName: "Japan", foreignName: "Japan"),
  Region(iso: "KE", englishName: "Kenya", foreignName: "Kenya"),
  Region(iso: "KR", englishName: "South Korea", foreignName: "South Korea"),
  Region(iso: "KW", englishName: "Kuwait", foreignName: "Kuwait"),
  Region(iso: "LB", englishName: "Lebanon", foreignName: "Lebanon"),
  Region(iso: "LC", englishName: "Saint Lucia", foreignName: "Saint Lucia"),
  Region(iso: "LI", englishName: "Liechtenstein", foreignName: "Liechtenstein"),
  Region(iso: "LT", englishName: "Lithuania", foreignName: "Lithuania"),
  Region(iso: "LU", englishName: "Luxembourg", foreignName: "Luxembourg"),
  Region(iso: "LV", englishName: "Latvia", foreignName: "Latvia"),
  Region(iso: "LY", englishName: "Libya", foreignName: "Libya"),
  Region(iso: "MA", englishName: "Morocco", foreignName: "Morocco"),
  Region(iso: "MC", englishName: "Monaco", foreignName: "Monaco"),
  Region(iso: "MD", englishName: "Moldova,", foreignName: "Moldova"),
  Region(iso: "ME", englishName: "Montenegro", foreignName: "Montenegro"),
  Region(iso: "MG", englishName: "Madagascar", foreignName: "Madagascar"),
  Region(iso: "MK", englishName: "Macedonia", foreignName: "Macedonia"),
  Region(iso: "ML", englishName: "Mali", foreignName: "Mali"),
  Region(iso: "MT", englishName: "Malta", foreignName: "Malta"),
  Region(iso: "MU", englishName: "Mauritius", foreignName: "Mauritius"),
  Region(iso: "MW", englishName: "Malawi", foreignName: "Malawi"),
  Region(iso: "MX", englishName: "Mexico", foreignName: "Mexico"),
  Region(iso: "MY", englishName: "Malaysia", foreignName: "Malaysia"),
  Region(iso: "MZ", englishName: "Mozambique", foreignName: "Mozambique"),
  Region(iso: "NE", englishName: "Niger", foreignName: "Niger"),
  Region(iso: "NG", englishName: "Nigeria", foreignName: "Nigeria"),
  Region(iso: "NI", englishName: "Nicaragua", foreignName: "Nicaragua"),
  Region(iso: "NL", englishName: "Netherlands", foreignName: "Netherlands"),
  Region(iso: "NO", englishName: "Norway", foreignName: "Norway"),
  Region(iso: "NZ", englishName: "New Zealand", foreignName: "New Zealand"),
  Region(iso: "OM", englishName: "Oman", foreignName: "Oman"),
  Region(iso: "PA", englishName: "Panama", foreignName: "Panama"),
  Region(iso: "PE", englishName: "Peru", foreignName: "Peru"),
  Region(iso: "PF", englishName: "French Polynesia", foreignName: "French Polynesia"),
  Region(iso: "PG", englishName: "Papua New Guinea", foreignName: "Papua New Guinea"),
  Region(iso: "PH", englishName: "Philippines", foreignName: "Philippines"),
  Region(iso: "PK", englishName: "Pakistan", foreignName: "Pakistan"),
  Region(iso: "PL", englishName: "Poland", foreignName: "Poland"),
  Region(iso: "PS", englishName: "Palestine", foreignName: "Palestine"),
  Region(iso: "PT", englishName: "Portugal", foreignName: "Portugal"),
  Region(iso: "PY", englishName: "Paraguay", foreignName: "Paraguay"),
  Region(iso: "QA", englishName: "Qatar", foreignName: "Qatar"),
  Region(iso: "RO", englishName: "Romania", foreignName: "Romania"),
  Region(iso: "RS", englishName: "Serbia", foreignName: "Serbia"),
  Region(iso: "RU", englishName: "Russia", foreignName: "Russia"),
  Region(iso: "SA", englishName: "Saudi Arabia", foreignName: "Saudi Arabia"),
  Region(iso: "SC", englishName: "Seychelles", foreignName: "Seychelles"),
  Region(iso: "SE", englishName: "Sweden", foreignName: "Sweden"),
  Region(iso: "SG", englishName: "Singapore", foreignName: "Singapore"),
  Region(iso: "SI", englishName: "Slovenia", foreignName: "Slovenia"),
  Region(iso: "SK", englishName: "Slovakia", foreignName: "Slovakia"),
  Region(iso: "SM", englishName: "San Marino", foreignName: "San Marino"),
  Region(iso: "SN", englishName: "Senegal", foreignName: "Senegal"),
  Region(iso: "SV", englishName: "El Salvador", foreignName: "El Salvador"),
  Region(iso: "SY", englishName: "Syrian Arab Republic", foreignName: "Syrian Arab Republic"),
  Region(iso: "TC", englishName: "Turks and Caicos Islands", foreignName: "Turks and Caicos Islands"),
  Region(iso: "TD", englishName: "Chad", foreignName: "Chad"),
  Region(iso: "TH", englishName: "Thailand", foreignName: "Thailand"),
  Region(iso: "TN", englishName: "Tunisia", foreignName: "Tunisia"),
  Region(iso: "TR", englishName: "Turkey", foreignName: "Turkey"),
  Region(iso: "TT", englishName: "Trinidad and Tobago", foreignName: "Trinidad and Tobago"),
  Region(iso: "TW", englishName: "Taiwan", foreignName: "Taiwan"),
  Region(iso: "TZ", englishName: "Tanzania", foreignName: "Tanzania"),
  Region(iso: "UA", englishName: "Ukraine", foreignName: "Ukraine"),
  Region(iso: "UG", englishName: "Uganda", foreignName: "Uganda"),
  Region(iso: "US", englishName: "United States of America", foreignName: "United States"),
  Region(iso: "UY", englishName: "Uruguay", foreignName: "Uruguay"),
  Region(iso: "VE", englishName: "Venezuela", foreignName: "Venezuela"),
  Region(iso: "XK", englishName: "Kosovo", foreignName: "Kosovo"),
  Region(iso: "YE", englishName: "Yemen", foreignName: "Yemen"),
  Region(iso: "ZA", englishName: "South Africa", foreignName: "South Africa"),
  Region(iso: "ZM", englishName: "Zambia", foreignName: "Zambia"),
  Region(iso: "ZW", englishName: "Zimbabwe", foreignName: "Zimbabwe"),
];
