// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgx1_i0Vqczg3THRb16bVrKy3vZeGbpoY',
    appId: '1:1024361335030:web:2035f1bb8745665b9d44d7',
    messagingSenderId: '1024361335030',
    projectId: 'watch-next-13',
    authDomain: 'watch-next-13.firebaseapp.com',
    storageBucket: 'watch-next-13.appspot.com',
    measurementId: 'G-M3LS7QVRFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHt-U93XGm4ZvKfj40_f2Lshuo72LN_I',
    appId: '1:1024361335030:android:6618d0d3f6cccd309d44d7',
    messagingSenderId: '1024361335030',
    projectId: 'watch-next-13',
    storageBucket: 'watch-next-13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTy-FUniF0tPYM1P0Q0TGuwSAR-8Or18',
    appId: '1:1024361335030:ios:ac1fc17361815c3c9d44d7',
    messagingSenderId: '1024361335030',
    projectId: 'watch-next-13',
    storageBucket: 'watch-next-13.appspot.com',
    iosBundleId: 'com.filippefrulli.watch-next',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTy-FUniF0tPYM1P0Q0TGuwSAR-8Or18',
    appId: '1:1024361335030:ios:a142a656dcd91a299d44d7',
    messagingSenderId: '1024361335030',
    projectId: 'watch-next-13',
    storageBucket: 'watch-next-13.appspot.com',
    iosBundleId: 'com.example.watchNext',
  );
}
